name: Planned maintenance variables

description: Set values that will be used by the planned-maintenance action

outputs:
  maintenance-window-start:
    description: "Time when the maintenance window will open.  After this point, the checklist will be enabled and the action will fail"
  maintenance-window-duration:
    description: "Number of milliseconds the maintenance window will remain open for"
  maintenance-url:
    description: "URL with more information about this maintenance, will be displayed in error output"

runs:
  using: "node12"
  main: "index.js"
